# Generated by Django 4.2.16 on 2024-11-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
                ('tikets', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('video', models.FileField(upload_to='static/videos')),
                ('img', models.ImageField(upload_to='static/images')),
                ('date_view', models.DateTimeField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefilms.category')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_teatre', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefilms.city')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefilms.region')),
                ('street_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefilms.street')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qvantity', models.IntegerField()),
                ('type_pay', models.CharField(choices=[('card', 'Card'), ('cash', 'cash')], max_length=100)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefilms.films')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefilms.user')),
            ],
        ),
        migrations.AddField(
            model_name='films',
            name='teatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinefilms.teatre'),
        ),
    ]
