# Generated by Django 4.2.16 on 2024-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinefilms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teatre',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
